### ISSUE TITLE
Docker Bug - Missing Folders and Module

### ISSUE THREAD

**Issue by MatzeFix** [viasite/site-audit-seo#18]
Hey Guys,

I really like your solution to get some statistics about homepages and SEO-Stuff.

I tried your provides solution and it works perfectly.

After it I tried to run the docker-compose section and got these errors:

**$ docker-compose up -d**

> ERROR: build path /var/docker/config/pagespeed-insights-lighthouse/site-audit-seo/data/front either does not exist, is not accessible, or is not a valid URL.

So I created the folder-path
**$ mkdir -p data/front**

**$ docker-compose up -d**

> sas-backend is always restarting
**$ docker ps**
CONTAINER ID   IMAGE                                  COMMAND                  CREATED          STATUS                        PORTS                                                                                                                                                                                         NAMES
e1510237a6a4   viasite/site-audit-seo:latest          "docker-entrypoint.s…"   16 seconds ago   Restarting (1) 1 second ago                                                                                                                                                                                                 sas-backend

**$ docker logs sas-backend**

> > site-audit-seo@5.1.4 server /app
> node src/server.js

loaded plugins:  export-influxdb
Create empty package.json in data
internal/fs/utils.js:307
    throw err;
    ^

Error: EACCES: permission denied, copyfile './package-data.json' -> 'data/package.json'
    at Object.copyFileSync (fs.js:1991:3)
    at Object.exports.initDataDir (/app/src/utils.js:22:8)
    at Object.<anonymous> (/app/src/server.js:17:7)
    at Module._compile (internal/modules/cjs/loader.js:1063:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1092:10)
    at Module.load (internal/modules/cjs/loader.js:928:32)
    at Function.Module._load (internal/modules/cjs/loader.js:769:14)
    at Function.executeUserEntryPoint [as runMain] (internal/modules/run_main.js:72:12)
    at internal/main/run_main_module.js:17:47 {
  errno: -13,
  syscall: 'copyfile',
  code: 'EACCES',
  path: './package-data.json',
  dest: 'data/package.json'
}
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! site-audit-seo@5.1.4 server: `node src/server.js`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the site-audit-seo@5.1.4 server script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/node/.npm/_logs/2021-06-09T15_23_14_901Z-debug.log

I added the the App Path in docker-compose File
 volumes:
    - .:/app <------------
    - ./data:/app/data
    - ./data/reports:/app/data/reports
    - ./data/db-docker.json:/app/data/db.json

**$ docker-compose down
$ docker-compose up -d
$ docker logs sas-backend**

After this I get this error
> site-audit-seo@5.1.4 server /app
> node src/server.js

internal/modules/cjs/loader.js:883
  throw err;
  ^

Error: Cannot find module 'lowdb'
Require stack:
- /app/src/server.js
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:880:15)
    at Function.Module._load (internal/modules/cjs/loader.js:725:27)
    at Module.require (internal/modules/cjs/loader.js:952:19)
    at require (internal/modules/cjs/helpers.js:88:18)
    at Object.<anonymous> (/app/src/server.js:2:15)
    at Module._compile (internal/modules/cjs/loader.js:1063:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1092:10)
    at Module.load (internal/modules/cjs/loader.js:928:32)
    at Function.Module._load (internal/modules/cjs/loader.js:769:14)
    at Function.executeUserEntryPoint [as runMain] (internal/modules/run_main.js:72:12) {
  code: 'MODULE_NOT_FOUND',
  requireStack: [ '/app/src/server.js' ]
}
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! site-audit-seo@5.1.4 server: `node src/server.js`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the site-audit-seo@5.1.4 server script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.
npm WARN Local package.json exists, but node_modules missing, did you mean to install?

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/node/.npm/_logs/2021-06-09T15_26_01_533Z-debug.log

Now I'm without ideas, I hope you can help me or fix the image :)

Thanks for your great work :)

**Comment by popstas** [comment]
Hello!

1. Try `npm install` in project root, it can fix `Cannot find module 'lowdb'`.
2. Try create `data/reports` directory in project root.

**Comment by MatzeFix** [comment]
> 
> 
> Hello!
> 
>     1. Try `npm install` in project root, it can fix `Cannot find module 'lowdb'`.
> 
>     2. Try create `data/reports` directory in project root.

Hey Popstas,

that doesn't help - it's already in der Dockerfile included and new builded :) 

Is there is another way to start the docker from scratch?

Thank you :)

**Comment by popstas** [comment]
Will check at next week.

**Comment by popstas** [comment]
Hello!
I just tested zero install with docker-compose, it was broken:

1. Need to git clone data/front, full install commands:

``` bash
git clone https://github.com/viasite/site-audit-seo
cd site-audit-seo
git clone https://github.com/viasite/site-audit-seo-viewer data/front
docker-compose pull
docker-compose up -d
```

2. Need to remove `./data/db-docker.json:/app/data/db.json` in docker-compose mounts.

**Comment by MatzeFix** [comment]
Hey ho,

thanks for taking care and the time :) 

I tried your Steps and get the following errror:

> site-audit-seo@5.1.5 server /app
> node src/server.js

loaded plugins:  export-influxdb
Create empty package.json in data
internal/fs/utils.js:307
    throw err;
    ^

Error: EACCES: permission denied, copyfile './package-data.json' -> 'data/package.json'
    at Object.copyFileSync (fs.js:1991:3)
    at Object.exports.initDataDir (/app/src/utils.js:22:8)
    at Object.<anonymous> (/app/src/server.js:17:7)
    at Module._compile (internal/modules/cjs/loader.js:1063:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1092:10)
    at Module.load (internal/modules/cjs/loader.js:928:32)
    at Function.Module._load (internal/modules/cjs/loader.js:769:14)
    at Function.executeUserEntryPoint [as runMain] (internal/modules/run_main.js:72:12)
    at internal/main/run_main_module.js:17:47 {
  errno: -13,
  syscall: 'copyfile',
  code: 'EACCES',
  path: './package-data.json',
  dest: 'data/package.json'
}
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! site-audit-seo@5.1.5 server: `node src/server.js`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the site-audit-seo@5.1.5 server script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/node/.npm/_logs/2021-06-23T21_50_23_866Z-debug.log


Thank you :)

**Comment by popstas** [comment]
Try `mkdir data`. I tried clean install in Windows 10, it was launched without `mkdir`. What your OS?

**Comment by MatzeFix** [comment]
Hey @popstas 

Took again a try and the containers are running :)

I try it also on Windows 10 and Docker Engine :)

But now I get the following Error in Browser - tried on Firefox and Chrome.
Cannot read property 'default' of undefined
An error occurred while rendering the page. Check developer tools console for details.

Attached you will find a screenshot of the whole error in Browser.

![Screenshot_VueJS_Error](https://user-images.githubusercontent.com/50321392/124841389-669ed480-df8d-11eb-996d-bf2524902fbe.png)

**Comment by adoerler** [comment]
Hi @MatzeFix ,

I'm also got the error `Cannot read property 'default' of undefined`.

Looking deeper show, that the default columns config etc. is missing.

The problem seems to be a missing `JSON_URL` in the `.env` file.
To give it a try you can add `https://site-audit.viasite.ru/reports/blog.popstas.ru-default.json` there, `docker-compose up` again and eventually delete the website application cache.

In my case the frontend starts up correctly, but now I've to figure out what JSON-File should be placed inside `.env` ;-)

BR
Andreas

**Comment by popstas** [comment]
I've added zero-knowledge install in April 2024 - https://github.com/viasite/site-audit-seo?tab=readme-ov-file#zero-knowledge-install
