### ISSUE TITLE
Licensing recommendations

### ISSUE THREAD

**Issue by TechnologyClassroom** [viasite/site-audit-seo#26]
I see the license is listed as [ISC](https://github.com/viasite/site-audit-seo/blob/master/package.json#L24).  I would recommend using a copyleft license instead as successful permissively licensed projects tend to be used by companies within proprietary projects and they typically never give back.  If you go with copyleft, I would recommend [AGPL-3.0-or-later](https://spdx.org/licenses/AGPL-3.0-or-later.html) or at least GPL-3.0-or-later.  If you stick with a permissive license, I would recommend Apache-2.0.

I would further recommend making a license file in the root directory of the repo.  If you create a LICENSE file, this information will be displayed within the first page view for the project. GitHub walks you through the steps after naming a new file `LICENSE`.

**Comment by popstas** [comment]
@TechnologyClassroom , thank you, the license was changed!
