### ISSUE TITLE
Сделайте докер

### ISSUE THREAD

**Issue by mytab0r** [viasite/site-audit-seo#5]
Это очень полезный инструмент и будет очень удобно запускать его в докер контейнере.

**Comment by popstas** [comment]
Сделаю при случае, но не вижу, как это нам поможет. В нашем случае проще было `npm i -g site-audit-seo`.

Кстати, интересно, как именно вы используете утилиту?

**Comment by popstas** [comment]
@mytab0r , появился докер в #7, пока что только в master ветке, скоро будет и релиз.
